
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
    interface RU {
    public void updateAlamat();
    public void updateNomor();
    public void updateNama();
}
/**
 *
 * @author RAFLY
 */
public class Profile extends javax.swing.JInternalFrame {
    Connection con = koneksiDatabase.BukaKoneksi();
    ResultSet rs;
    Statement stm;
    String nomortelepon;
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bIF = (BasicInternalFrameUI)this.getUI();
        bIF.setNorthPane(null);
    }
    public Profile(String aidi) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bIF = (BasicInternalFrameUI)this.getUI();
        bIF.setNorthPane(null);
        try {
        stm = con.createStatement();
        rs = stm.executeQuery("select * from data where id = '" + aidi + "'");
        if (rs.next()) {  
        this.nomortelepon = rs.getString("nomor_telepon");
        id.setText(rs.getString("id"));
        nama.setText(rs.getString("username"));   
        alamat.setText(rs.getString("alamat"));
        nomorT.setText(nomortelepon.substring(1, nomortelepon.length()));       
        }
        
        }        
        catch (Exception e) {
        JOptionPane.showConfirmDialog(null, e);
        }
        id.setText(aidi);
        nama.setEditable(false);
        id.setEditable(false);
    }
    
    public void updateNama() {
    try {
        stm = con.createStatement();
        int aidi = Integer.parseInt(id.getText());
        stm.executeUpdate("Update data set username = '" + nama.getText() + "' where id = '" + aidi + "'");
        nama.setEditable(false);
        JOptionPane.showMessageDialog(null, "Nama berhasil diganti, Silahkan Log out terlebih dahulu "+ "\n" +"untuk merefresh username", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    
    }
    public void updateNomor() {
    try {
        stm = con.createStatement();
        //nomorTelepon = nomorTelepon.replaceFirst("^0+(?!$)", "");
        int aidi = Integer.parseInt(id.getText());
        stm.executeUpdate("update data set nomor_telepon = '0" + nomorT.getText() + "' where id = '" + aidi + "'");
        JOptionPane.showMessageDialog(null, "Nomor Telepon berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (Exception e) {
        JOptionPane.showConfirmDialog(null, e);
        }
    }
    public void updateAlamat() {
    try {
        stm = con.createStatement();
        int aidi = Integer.parseInt(id.getText());
        stm.executeUpdate("update data set alamat = '" + alamat.getText() + "' where id = '" + aidi + "'");
        JOptionPane.showMessageDialog(null, "Alamat berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        JOptionPane.showConfirmDialog(null, e);
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomorT = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        simpanNT = new javax.swing.JButton();
        simpanA = new javax.swing.JButton();
        simpanN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 500));

        jPanel2.setBackground(new java.awt.Color(207, 219, 218));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Profile");

        nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaMouseClicked(evt);
            }
        });

        simpanNT.setText("Simpan");
        simpanNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanNTActionPerformed(evt);
            }
        });

        simpanA.setText("Simpan");
        simpanA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanAActionPerformed(evt);
            }
        });

        simpanN.setText("Simpan");
        simpanN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanNActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Nomor Telepon");

        jLabel4.setText("Alamat");

        jLabel5.setText("id");

        jLabel6.setText("+62");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorT, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanN)
                            .addComponent(simpanA)
                            .addComponent(simpanNT))))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanNT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseClicked
        // TODO add your handling code here:
        int apakah = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengganti nama ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (apakah == 0) {
            nama.setEditable(true);
        } else {
            nama.setEditable(false);
        }
    }//GEN-LAST:event_namaMouseClicked

    private void simpanNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanNTActionPerformed
        // TODO add your handling code here:
        updateNomor();
    }//GEN-LAST:event_simpanNTActionPerformed

    private void simpanAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanAActionPerformed
        // TODO add your handling code here:
        updateAlamat();
    }//GEN-LAST:event_simpanAActionPerformed

    private void simpanNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanNActionPerformed
        // TODO add your handling code here:
        updateNama();
    }//GEN-LAST:event_simpanNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomorT;
    private javax.swing.JButton simpanA;
    private javax.swing.JButton simpanN;
    private javax.swing.JButton simpanNT;
    // End of variables declaration//GEN-END:variables
}
